# Generated by Django 3.1.6 on 2021-02-09 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, db_index=True, max_length=300, verbose_name='Заголовок')),
                ('url', models.URLField(blank=True, max_length=300, verbose_name='Ссылка')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Дата публикации')),
            ],
            options={
                'verbose_name': 'Последние новости',
                'verbose_name_plural': 'Последние новости',
                'ordering': ['-created'],
            },
        ),
    ]
